### ISSUE TITLE
errors running on linux

### ISSUE THREAD

**Issue by bvs23bkv33** [Alexander-94/calm_down_game#3]
ivan@debian:~/calm_down_game$ Release/calm_down
Irrlicht Engine version 1.8.4
Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3 (2019-02-02) x86_64
Using plain X visual
Could not load terrain, because file could not be opened.: img/terrain/map.png
Could not open file of texture: img/terrain/texture.png
Помилка адресування

**Comment by bvs23bkv33** [comment]
на самом деле оно запускается, если зайти в папку Release и стартовать оттуда
![2019-02-23 12-08-14](https://user-images.githubusercontent.com/7599687/53284991-ebde1180-3763-11e9-8866-f6eb218f70f7.png)
но мне надо настроить так чтоб eclipse тоже мог стартовать

**Comment by bvs23bkv33** [comment]
мне, наверное, надо папку calm_down переименовать в папку src, а на её место складывать исполняемый файл, хотя папок с ресурсами img и media в корне проекта нет
короче, ещё надо подумать потому что пока это нехорошее решение

**Comment by bvs23bkv33** [comment]
настроил, пока закрываю

**Comment by Alexander-94** [comment]
Можно и переменовать если надо
